version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: se68_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  socket:
    build: ./frontend/socket-server
    container_name: se68_socket
    restart: always
    ports:
      - "3001:3001"
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: se68_backend
    restart: always
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
      FRONTEND_URL: http://${DOMAIN_NAME}
      SMTP_SENDER_EMAIL: ${SMTP_SENDER_EMAIL}
      SMTP_SENDER_NAME: ${SMTP_SENDER_NAME}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_USERNAME: ${SMTP_USERNAME}
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://${DOMAIN_NAME}:8080
        NEXT_PUBLIC_SOCKET_URL: http://${DOMAIN_NAME}:3001
    container_name: se68_frontend
    restart: always
    ports:
      - "80:5173"
    depends_on:
      - backend
      - socket
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge