services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx_config/custom.conf:/etc/nginx/conf.d/custom.conf:ro
    networks:
      - app-network
    restart: always

  nginx-proxy-letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-letsencrypt
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx_config/custom.conf:/etc/nginx/conf.d/custom.conf:ro
      - acme:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: b6640583@g.sut.ac.th
      NGINX_PROXY_CONTAINER: nginx-proxy
    networks:
      - app-network
    restart: always

  db:
    image: postgres:15-alpine
    container_name: se68_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: se68_minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app-network

  socket:
    build: ./frontend/socket-server
    container_name: se68_socket
    restart: always
    expose:
      - "3001"
    environment:
      FRONTEND_URL: https://capstonehub.me
      VIRTUAL_HOST: socket.capstonehub.me
      VIRTUAL_PORT: 3001
      LETSENCRYPT_HOST: socket.capstonehub.me
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: se68_backend
    env_file:
      - .env
    restart: always
    depends_on:
      - db
      - minio
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/lib:/app/lib
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
      FRONTEND_URL: https://capstonehub.me
      SMTP_SENDER_EMAIL: ${SMTP_SENDER_EMAIL}
      SMTP_SENDER_NAME: ${SMTP_SENDER_NAME}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SOCKET_SERVICE_URL: "http://socket:3001"
      GIN_MODE: release
      APP_ENV: production
      COOKIE_DOMAIN: capstonehub.me
      VIRTUAL_HOST: api.capstonehub.me
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: api.capstonehub.me
      MINIO_ENDPOINT: minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    expose:
      - "8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: https://api.capstonehub.me
        NEXT_PUBLIC_SOCKET_URL: https://socket.capstonehub.me
        NEXT_PUBLIC_STORAGE_URL: https://api.capstonehub.me/team07api/storage
        NEXT_PUBLIC_BACKEND_URL: https://api.capstonehub.me/team07api
    container_name: se68_frontend
    restart: always
    expose:
      - "5173"
    depends_on:
      - backend
      - socket
    environment:
      NEXT_PUBLIC_API_URL: https://api.capstonehub.me
      NEXT_PUBLIC_SOCKET_URL: https://socket.capstonehub.me
      NEXT_PUBLIC_STORAGE_URL: https://api.capstonehub.me/team07api/storage
      VIRTUAL_HOST: capstonehub.me,www.capstonehub.me
      VIRTUAL_PORT: 5173
      LETSENCRYPT_HOST: capstonehub.me,www.capstonehub.me
    networks:
      - app-network

volumes:
  pgdata:
  minio-data:
  certs:
  vhost:
  html:
  acme:

networks:
  app-network:
    driver: bridge
