name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: azureuser
          password: ${{ secrets.PASSWORD }}
          script: |
            # 1. เข้า folder
            cd /home/azureuser/team07

            # 2. บังคับ Code ให้ตรงกับ GitHub
            git fetch --all
            git reset --hard origin/main
            
            mkdir -p backend/uploads/chats backend/uploads/news backend/uploads/progress backend/uploads/topics
            chmod -R 777 backend/uploads

            # 3. สร้างไฟล์ .env
            cat <<EOF > .env
            # --- Database ---
            DB_HOST=db
            DB_PORT=5432
            DB_USER=rattasat
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=se_db

            # --- Server ---
            DOMAIN_NAME=capstonehub.me
            
            # --- JWT & Auth ---
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            REFRESH_SECRET_KEY=${{ secrets.REFRESH_SECRET_KEY }}
            ACCESS_TOKEN_TTL=4h
            REFRESH_TOKEN_TTL=168h
            RESET_TOKEN_TTL=8m
            REFRESH_COOLDOWN=8s
            COOKIE_DOMAIN=capstonehub.me

            # --- Email ---
            SMTP_SENDER_EMAIL=b6640583@g.sut.ac.th
            SMTP_SENDER_NAME="Capstone Hub"
            SMTP_HOST=smtp.sendgrid.net
            SMTP_PORT=587
            SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
            SMTP_USERNAME=apikey
            EOF

            # 4. Restart Container
            docker compose down

            # 4.1 สั่ง Build ใหม่แบบ
            docker compose build

            # 4.2 รันขึ้นมาใหม่แบบบังคับสร้าง Container ใหม่
            docker compose up -d --force-recreate

            # 5. ล้างขยะ
            docker image prune -f